global:
  extensions:
    extAuth:
      deployment:
        floatingUserId: true
        fsGroup: ""
    rateLimit:
      deployment:
        floatingUserId: true
oberservability:
  deployment:
    floatingUserId: true
redis:
  deployment:
    floatingUserId: true
    enablePodSecurityContext: false
gloo:
  gloo:
    deployment:
      floatingUserId: true
  discovery:
    deployment:
      floatingUserId: true
      enablePodSecurityContext: false
  gateway:
    deployment:
      floatingUserId: true
    certGenJob:
      floatingUserId: true
  oberservability:
    deployment:
      floatingUserId: true
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        floatingUserId: true
        enablePodSecurityContext: false
gloo-fed:
  enabled: false
  glooFedApiserver:
    floatingUserId: true
prometheus:
  enabled: false
grafana:
  defaultInstallationEnabled: false
